#
# Adapted from LOFFER template
#

name: Astronomy Graduate Student Congress
description: Connecting Graduate Students in Astronomy Across Institutions

url: 

baseurl: /astro-grad-congress

# logo (300px × 300px) add rawgithubuserconent link 
avatar: images/logo.png

# favicon (64px × 64px 
favicon: images/logo.png

navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Team
    url: /team
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

collections:
  representatives:
    output: true

paginate: 8

excerpt_separator: <!-- more -->

footer-links: 
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: #youremailaddress@mail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: astro-grad-congress #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

footer-text: Copyright (c) 2024 

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

